headless: false
service_type: 'Customer Ltd Warranty'
service_delivery_type: "On-Site"
customer_search_field: 'Company'
input_csv_path: 'config/adp_warranty_claims.csv'
state_csv_path: 'config/adp_warranty_claims_export.csv'
url: "https://csp.lenovo.com/irj/portal"
max_attempts: 5
failure_sleep_times:
  1: 0.25
  2: 1
  3: 2
  4: 5
  5: 10
date_format: '%d.%m.%Y'
log_path: 'app.log'
submit_claim: false # Enable to submit claims.
explicit_wait_time: 8
errors:
  exceeds_service_date_threshold: 'Service date must be no more than 15 calendar days in the past.'